spring:
  cloud:
    gateway:
      globalcors:
         cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
          - id: admin-service
            uri:
              lb://admin-service
            predicates:
              - Path=/admin/**
            filters:
              - name: AuthenticationFilter

          - id: user-service
            uri:
              lb://user-service
            predicates:
              - Path=/users/**
            filters:
              - name: AuthenticationFilter


          - id: worker-service
            uri:
              lb://worker-service
            predicates:
              - Path=/workers/**
            filters:
              - name: AuthenticationFilter


          - id: booking-service
            uri:
              lb://booking-service
            predicates:
              - Path=/booking/**
            filters:
              - name: AuthenticationFilter


          - id: auth-service
            uri:
              lb://auth-service
            predicates:
              - Path=/api/v1/auth/**
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
